// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/proto/coordinator.proto

package coordinatorv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SignalType int32

const (
	SignalType_SIGNAL_TYPE_UNSPECIFIED SignalType = 0
	SignalType_SIGNAL_ICE_CANDIDATE    SignalType = 1
	SignalType_SIGNAL_ICE_OFFER        SignalType = 2
	SignalType_SIGNAL_ICE_ANSWER       SignalType = 3
)

// Enum value maps for SignalType.
var (
	SignalType_name = map[int32]string{
		0: "SIGNAL_TYPE_UNSPECIFIED",
		1: "SIGNAL_ICE_CANDIDATE",
		2: "SIGNAL_ICE_OFFER",
		3: "SIGNAL_ICE_ANSWER",
	}
	SignalType_value = map[string]int32{
		"SIGNAL_TYPE_UNSPECIFIED": 0,
		"SIGNAL_ICE_CANDIDATE":    1,
		"SIGNAL_ICE_OFFER":        2,
		"SIGNAL_ICE_ANSWER":       3,
	}
)

func (x SignalType) Enum() *SignalType {
	p := new(SignalType)
	*p = x
	return p
}

func (x SignalType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SignalType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_coordinator_proto_enumTypes[0].Descriptor()
}

func (SignalType) Type() protoreflect.EnumType {
	return &file_api_proto_coordinator_proto_enumTypes[0]
}

func (x SignalType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SignalType.Descriptor instead.
func (SignalType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_coordinator_proto_rawDescGZIP(), []int{0}
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicKey     string                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AuthKey       string                 `protobuf:"bytes,3,opt,name=auth_key,json=authKey,proto3" json:"auth_key,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_api_proto_coordinator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_coordinator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_coordinator_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *RegisterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterRequest) GetAuthKey() string {
	if x != nil {
		return x.AuthKey
	}
	return ""
}

func (x *RegisterRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	VirtualIp     string                 `protobuf:"bytes,2,opt,name=virtual_ip,json=virtualIp,proto3" json:"virtual_ip,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	NetworkCidr   string                 `protobuf:"bytes,4,opt,name=network_cidr,json=networkCidr,proto3" json:"network_cidr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_api_proto_coordinator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_coordinator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_coordinator_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RegisterResponse) GetVirtualIp() string {
	if x != nil {
		return x.VirtualIp
	}
	return ""
}

func (x *RegisterResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *RegisterResponse) GetNetworkCidr() string {
	if x != nil {
		return x.NetworkCidr
	}
	return ""
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_api_proto_coordinator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_coordinator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_coordinator_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HeartbeatRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerTime    int64                  `protobuf:"varint,1,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	UpdatedPeers  []string               `protobuf:"bytes,2,rep,name=updated_peers,json=updatedPeers,proto3" json:"updated_peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_api_proto_coordinator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_coordinator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_coordinator_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatResponse) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

func (x *HeartbeatResponse) GetUpdatedPeers() []string {
	if x != nil {
		return x.UpdatedPeers
	}
	return nil
}

type ListPeersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OnlineOnly    bool                   `protobuf:"varint,1,opt,name=online_only,json=onlineOnly,proto3" json:"online_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPeersRequest) Reset() {
	*x = ListPeersRequest{}
	mi := &file_api_proto_coordinator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPeersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPeersRequest) ProtoMessage() {}

func (x *ListPeersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_coordinator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPeersRequest.ProtoReflect.Descriptor instead.
func (*ListPeersRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_coordinator_proto_rawDescGZIP(), []int{4}
}

func (x *ListPeersRequest) GetOnlineOnly() bool {
	if x != nil {
		return x.OnlineOnly
	}
	return false
}

type ListPeersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peers         []*PeerInfo            `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPeersResponse) Reset() {
	*x = ListPeersResponse{}
	mi := &file_api_proto_coordinator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPeersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPeersResponse) ProtoMessage() {}

func (x *ListPeersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_coordinator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPeersResponse.ProtoReflect.Descriptor instead.
func (*ListPeersResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_coordinator_proto_rawDescGZIP(), []int{5}
}

func (x *ListPeersResponse) GetPeers() []*PeerInfo {
	if x != nil {
		return x.Peers
	}
	return nil
}

type GetPeerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPeerRequest) Reset() {
	*x = GetPeerRequest{}
	mi := &file_api_proto_coordinator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPeerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPeerRequest) ProtoMessage() {}

func (x *GetPeerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_coordinator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPeerRequest.ProtoReflect.Descriptor instead.
func (*GetPeerRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_coordinator_proto_rawDescGZIP(), []int{6}
}

func (x *GetPeerRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type PeerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PublicKey     string                 `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	VirtualIp     string                 `protobuf:"bytes,4,opt,name=virtual_ip,json=virtualIp,proto3" json:"virtual_ip,omitempty"`
	Online        bool                   `protobuf:"varint,5,opt,name=online,proto3" json:"online,omitempty"`
	LastSeen      int64                  `protobuf:"varint,6,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	Endpoints     []string               `protobuf:"bytes,7,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerInfo) Reset() {
	*x = PeerInfo{}
	mi := &file_api_proto_coordinator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerInfo) ProtoMessage() {}

func (x *PeerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_coordinator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerInfo.ProtoReflect.Descriptor instead.
func (*PeerInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_coordinator_proto_rawDescGZIP(), []int{7}
}

func (x *PeerInfo) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *PeerInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PeerInfo) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *PeerInfo) GetVirtualIp() string {
	if x != nil {
		return x.VirtualIp
	}
	return ""
}

func (x *PeerInfo) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

func (x *PeerInfo) GetLastSeen() int64 {
	if x != nil {
		return x.LastSeen
	}
	return 0
}

func (x *PeerInfo) GetEndpoints() []string {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

type SignalEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromNode      string                 `protobuf:"bytes,1,opt,name=from_node,json=fromNode,proto3" json:"from_node,omitempty"`
	ToNode        string                 `protobuf:"bytes,2,opt,name=to_node,json=toNode,proto3" json:"to_node,omitempty"`
	Type          SignalType             `protobuf:"varint,3,opt,name=type,proto3,enum=wink.coordinator.v1.SignalType" json:"type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalEnvelope) Reset() {
	*x = SignalEnvelope{}
	mi := &file_api_proto_coordinator_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalEnvelope) ProtoMessage() {}

func (x *SignalEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_coordinator_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalEnvelope.ProtoReflect.Descriptor instead.
func (*SignalEnvelope) Descriptor() ([]byte, []int) {
	return file_api_proto_coordinator_proto_rawDescGZIP(), []int{8}
}

func (x *SignalEnvelope) GetFromNode() string {
	if x != nil {
		return x.FromNode
	}
	return ""
}

func (x *SignalEnvelope) GetToNode() string {
	if x != nil {
		return x.ToNode
	}
	return ""
}

func (x *SignalEnvelope) GetType() SignalType {
	if x != nil {
		return x.Type
	}
	return SignalType_SIGNAL_TYPE_UNSPECIFIED
}

func (x *SignalEnvelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SignalEnvelope) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_api_proto_coordinator_proto protoreflect.FileDescriptor

const file_api_proto_coordinator_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/proto/coordinator.proto\x12\x13wink.coordinator.v1\"\xec\x01\n" +
	"\x0fRegisterRequest\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\tR\tpublicKey\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\bauth_key\x18\x03 \x01(\tR\aauthKey\x12N\n" +
	"\bmetadata\x18\x04 \x03(\v22.wink.coordinator.v1.RegisterRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8c\x01\n" +
	"\x10RegisterResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1d\n" +
	"\n" +
	"virtual_ip\x18\x02 \x01(\tR\tvirtualIp\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\x03R\texpiresAt\x12!\n" +
	"\fnetwork_cidr\x18\x04 \x01(\tR\vnetworkCidr\"I\n" +
	"\x10HeartbeatRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"Y\n" +
	"\x11HeartbeatResponse\x12\x1f\n" +
	"\vserver_time\x18\x01 \x01(\x03R\n" +
	"serverTime\x12#\n" +
	"\rupdated_peers\x18\x02 \x03(\tR\fupdatedPeers\"3\n" +
	"\x10ListPeersRequest\x12\x1f\n" +
	"\vonline_only\x18\x01 \x01(\bR\n" +
	"onlineOnly\"H\n" +
	"\x11ListPeersResponse\x123\n" +
	"\x05peers\x18\x01 \x03(\v2\x1d.wink.coordinator.v1.PeerInfoR\x05peers\")\n" +
	"\x0eGetPeerRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"\xc8\x01\n" +
	"\bPeerInfo\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"public_key\x18\x03 \x01(\tR\tpublicKey\x12\x1d\n" +
	"\n" +
	"virtual_ip\x18\x04 \x01(\tR\tvirtualIp\x12\x16\n" +
	"\x06online\x18\x05 \x01(\bR\x06online\x12\x1b\n" +
	"\tlast_seen\x18\x06 \x01(\x03R\blastSeen\x12\x1c\n" +
	"\tendpoints\x18\a \x03(\tR\tendpoints\"\xb3\x01\n" +
	"\x0eSignalEnvelope\x12\x1b\n" +
	"\tfrom_node\x18\x01 \x01(\tR\bfromNode\x12\x17\n" +
	"\ato_node\x18\x02 \x01(\tR\x06toNode\x123\n" +
	"\x04type\x18\x03 \x01(\x0e2\x1f.wink.coordinator.v1.SignalTypeR\x04type\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp*p\n" +
	"\n" +
	"SignalType\x12\x1b\n" +
	"\x17SIGNAL_TYPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14SIGNAL_ICE_CANDIDATE\x10\x01\x12\x14\n" +
	"\x10SIGNAL_ICE_OFFER\x10\x02\x12\x15\n" +
	"\x11SIGNAL_ICE_ANSWER\x10\x032\xc5\x03\n" +
	"\vCoordinator\x12W\n" +
	"\bRegister\x12$.wink.coordinator.v1.RegisterRequest\x1a%.wink.coordinator.v1.RegisterResponse\x12Z\n" +
	"\tHeartbeat\x12%.wink.coordinator.v1.HeartbeatRequest\x1a&.wink.coordinator.v1.HeartbeatResponse\x12Z\n" +
	"\tListPeers\x12%.wink.coordinator.v1.ListPeersRequest\x1a&.wink.coordinator.v1.ListPeersResponse\x12M\n" +
	"\aGetPeer\x12#.wink.coordinator.v1.GetPeerRequest\x1a\x1d.wink.coordinator.v1.PeerInfo\x12V\n" +
	"\x06Signal\x12#.wink.coordinator.v1.SignalEnvelope\x1a#.wink.coordinator.v1.SignalEnvelope(\x010\x01B/Z-winkyou/api/proto/coordinatorv1;coordinatorv1b\x06proto3"

var (
	file_api_proto_coordinator_proto_rawDescOnce sync.Once
	file_api_proto_coordinator_proto_rawDescData []byte
)

func file_api_proto_coordinator_proto_rawDescGZIP() []byte {
	file_api_proto_coordinator_proto_rawDescOnce.Do(func() {
		file_api_proto_coordinator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_coordinator_proto_rawDesc), len(file_api_proto_coordinator_proto_rawDesc)))
	})
	return file_api_proto_coordinator_proto_rawDescData
}

var file_api_proto_coordinator_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_coordinator_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_proto_coordinator_proto_goTypes = []any{
	(SignalType)(0),           // 0: wink.coordinator.v1.SignalType
	(*RegisterRequest)(nil),   // 1: wink.coordinator.v1.RegisterRequest
	(*RegisterResponse)(nil),  // 2: wink.coordinator.v1.RegisterResponse
	(*HeartbeatRequest)(nil),  // 3: wink.coordinator.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil), // 4: wink.coordinator.v1.HeartbeatResponse
	(*ListPeersRequest)(nil),  // 5: wink.coordinator.v1.ListPeersRequest
	(*ListPeersResponse)(nil), // 6: wink.coordinator.v1.ListPeersResponse
	(*GetPeerRequest)(nil),    // 7: wink.coordinator.v1.GetPeerRequest
	(*PeerInfo)(nil),          // 8: wink.coordinator.v1.PeerInfo
	(*SignalEnvelope)(nil),    // 9: wink.coordinator.v1.SignalEnvelope
	nil,                       // 10: wink.coordinator.v1.RegisterRequest.MetadataEntry
}
var file_api_proto_coordinator_proto_depIdxs = []int32{
	10, // 0: wink.coordinator.v1.RegisterRequest.metadata:type_name -> wink.coordinator.v1.RegisterRequest.MetadataEntry
	8,  // 1: wink.coordinator.v1.ListPeersResponse.peers:type_name -> wink.coordinator.v1.PeerInfo
	0,  // 2: wink.coordinator.v1.SignalEnvelope.type:type_name -> wink.coordinator.v1.SignalType
	1,  // 3: wink.coordinator.v1.Coordinator.Register:input_type -> wink.coordinator.v1.RegisterRequest
	3,  // 4: wink.coordinator.v1.Coordinator.Heartbeat:input_type -> wink.coordinator.v1.HeartbeatRequest
	5,  // 5: wink.coordinator.v1.Coordinator.ListPeers:input_type -> wink.coordinator.v1.ListPeersRequest
	7,  // 6: wink.coordinator.v1.Coordinator.GetPeer:input_type -> wink.coordinator.v1.GetPeerRequest
	9,  // 7: wink.coordinator.v1.Coordinator.Signal:input_type -> wink.coordinator.v1.SignalEnvelope
	2,  // 8: wink.coordinator.v1.Coordinator.Register:output_type -> wink.coordinator.v1.RegisterResponse
	4,  // 9: wink.coordinator.v1.Coordinator.Heartbeat:output_type -> wink.coordinator.v1.HeartbeatResponse
	6,  // 10: wink.coordinator.v1.Coordinator.ListPeers:output_type -> wink.coordinator.v1.ListPeersResponse
	8,  // 11: wink.coordinator.v1.Coordinator.GetPeer:output_type -> wink.coordinator.v1.PeerInfo
	9,  // 12: wink.coordinator.v1.Coordinator.Signal:output_type -> wink.coordinator.v1.SignalEnvelope
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_api_proto_coordinator_proto_init() }
func file_api_proto_coordinator_proto_init() {
	if File_api_proto_coordinator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_coordinator_proto_rawDesc), len(file_api_proto_coordinator_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_coordinator_proto_goTypes,
		DependencyIndexes: file_api_proto_coordinator_proto_depIdxs,
		EnumInfos:         file_api_proto_coordinator_proto_enumTypes,
		MessageInfos:      file_api_proto_coordinator_proto_msgTypes,
	}.Build()
	File_api_proto_coordinator_proto = out.File
	file_api_proto_coordinator_proto_goTypes = nil
	file_api_proto_coordinator_proto_depIdxs = nil
}
