FROM golang:1.23 AS builder

WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
ARG TARGETOS
ARG TARGETARCH
RUN CGO_ENABLED=0 GOOS=${TARGETOS:-linux} GOARCH=${TARGETARCH:-amd64} go build -o /out/wink-coordinator ./cmd/wink-coordinator

FROM gcr.io/distroless/static-debian12

COPY --from=builder /out/wink-coordinator /usr/local/bin/wink-coordinator
ENTRYPOINT ["/usr/local/bin/wink-coordinator"]
